### ISSUE TITLE
Menu shows up

### ISSUE THREAD

**Issue by howard445** [deadkex/StrandedDeep_Waypoints#1]
i have the epic games store version i got the menu to show up but how do i navigate the menu because my mouse is stuck being the camera i can't go over to click on the menu at all i have to pause to click on anything then when i create one i dont see it when i unpause

**Comment by howard445** [comment]
ok after trying a bunch of time i have got it to open but is there any way to make the way point bigger change the color and or work with split screen

**Comment by deadkex** [comment]
- default hideallwaypoints setting is now false
- size of waypoints can now be adjusted
- waypoints automatically get saved after creating a new one

Color change might come in the future but only if its actually needed.
I will not be adding support for splitscreen because they are working on coop.

Have fun :)
